### ISSUE TITLE
Link issues in XML sitemap

### ISSUE THREAD

**Issue by lembitk** [adrian3/whisper#4]
There seem to be too many URLs in Whisper-generated [XML](https://adrian3.com/sitemap.xml) [sitemaps](https://adrian3.github.io/whisper/sitemap.xml), a subset of them broken. 

For example, the [adrian3.com XML sitemap](https://adrian3.com/sitemap.xml): 

  - starts with a list of `.html` files under `writing/` where all the URLs miss a forward slash `/` after the domain name (`adrian3.comwriting` vs. `adrian3.com/writing`); 
  - then the list of `.html` files under `writing/` is repeated with correct URLs (`adrian3.com/writing`); 
  - then a listing of all other files follows, containing further duplicates (but this time none misses the `/`) -- e.g. 2 * `<url><loc>https://adrian3.com/timeline.html</loc></url>`, 2 * `<url><loc>https://adrian3.com/aotld/chapter9.html</loc></url>` etc. 

It seems to me the loop(s) building this list might need another look.

**Comment by adrian3** [comment]
Thanks again for finding my mistakes @lembitk ! I believe this has been corrected now.
